[window]
title = "GfX-Engine Minimal POC"
width = 1920
height = 1080
fullscreen = true
vsync = true
scaling_quality = "pixelart"
virtual_width = 480
virtual_height = 270
background_color = [0, 0, 0]
camera_tightness = 0.5
camera_slow_zone = 0.05
camera_fast_zone = 0.4
camera_vertical_snap_threshold = 0.1
camera_vertical_tightness = 0.1
camera_falling_tightness = 0.9
camera_falling_velocity_threshold = 1.0
camera_lookahead_distance = 100.0
camera_smoothing_speed = 0.1

[input]
left = "Left"
right = "Right"
jump = "Space"
quit = "Escape"
debug_toggle = "F1"

[debug]
show_debug_info = false
debug_draw_collision_boxes = true
text_start_x = 10
text_start_y = 100
text_line_spacing = 30

[physics]
gravity = 3200.0
max_speed = 220.0
entity_max_fall_speed = 600.0
acceleration = 800.0
deceleration = 1000.0
jump_strength = -550.0
jump_hold_force = 1700.0
max_jump_time = 15
air_control_factor = 0.3
velocity_threshold = 1.0
air_control_damping = 2.0

[game]
start_level = "assets/levels/world_1_level_1/level.tmx"
