[window]
title = "GfX-Engine Minimal POC"
width = 1920
height = 1080
fullscreen = true
vsync = true
scaling_quality = "pixelart"
virtual_width = 1920
virtual_height = 1080
background_color = [0, 0, 0]
camera_tightness = 0.5
camera_slow_zone = 0.05
camera_fast_zone = 0.4
camera_vertical_snap_threshold = 0.1
camera_vertical_tightness = 0.1
camera_falling_tightness = 0.9
camera_falling_velocity_threshold = 1.0
camera_lookahead_distance = 100.0

[input]
left = "Left"
right = "Right"
jump = "Space"
quit = "Escape"
debug_toggle = "F1"

[debug]
show_debug_info = true
debug_draw_collision_boxes = true

[physics]
gravity = 0.9
max_speed = 4.0
entity_max_fall_speed = 10.0
acceleration = 0.5
deceleration = 0.5

jump_strength = -9.0
jump_hold_force = 0.45
max_jump_time = 15
